// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { AuthChangeEvent, Session } from "@supabase/supabase-js";
import type { Database } from "./types";

type MockSupabaseClient = {
  from: (table: string) => {
    select: () => Promise<{ data: never[]; error: null }>;
    update: () => {
      eq: () => Promise<{ error: null }>;
    };
    eq: () => object;
  };
  storage: {
    createBucket: () => Promise<object>;
    from: (bucket: string) => {
      upload: () => Promise<{ data: null; error: null }>;
      getPublicUrl: (fileName: string) => { data: { publicUrl: string } };
    };
  };
  auth: {
    getSession: () => Promise<{ data: { session: Session | null }; error: null }>;
    onAuthStateChange: (callback: (event: AuthChangeEvent, session: Session | null) => void) => {
      data: { subscription: { unsubscribe(): void } };
    };
    signInWithOtp: () => Promise<{ data: null; error: Error }>;
    signOut: () => Promise<{ error: null }>;
  };
};

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] Missing env vars – using mock client for local dev");
    // Minimal mock client with only the methods used in the admin panel
    const mockClient: MockSupabaseClient = {
      from: (_table: string) => ({
        select: async () => ({ data: [], error: null }),
        update: () => ({ eq: async () => ({ error: null }) }),
        eq: () => ({}) as object,
      }),
      storage: {
        createBucket: async () => ({}) as object,
        from: (_bucket: string) => ({
          upload: async () => ({ data: null, error: null }),
          getPublicUrl: (_fileName: string) => ({ data: { publicUrl: "" } }),
        }),
      },
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        onAuthStateChange: (
          callback: (event: AuthChangeEvent, session: Session | null) => void,
        ) => {
          void callback;
          return { data: { subscription: { unsubscribe() {} } } };
        },
        signInWithOtp: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        signOut: async () => ({ error: null }),
      },
    };
    return mockClient;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  // Existing proxy getter
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

/**
 * Upload a partner logo to Supabase storage and update the partner record.
 * @param partnerId - The ID of the partner.
 * @param file - The File object (JPG, PNG, SVG).
 * @returns The public URL of the uploaded logo.
 */
export async function uploadPartnerLogo(partnerId: string, file: File): Promise<string> {
  if (!_supabase) _supabase = createSupabaseClient();

  // If no Supabase configured, fall back to localStorage (base64)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined);
  if (!SUPABASE_URL) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const dataUrl = reader.result as string;
        // Dynamically import to avoid circular dep issues
        import("@/lib/initiative-store")
          .then(({ savePartnerLogo }) => {
            savePartnerLogo(partnerId, dataUrl);
            resolve(dataUrl);
          })
          .catch(reject);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }

  const bucket = "partner-logos";
  try {
    // Fix: createBucket is on storage root, not storage.from()
    await _supabase.storage.createBucket(bucket, { public: true }).catch(() => {});
    const fileExt = file.name.split(".").pop();
    const fileName = `${partnerId}.${fileExt}`;
    const { error } = await _supabase.storage.from(bucket).upload(fileName, file, { upsert: true });
    if (error) throw error;
    // Fix: v2 API uses data.publicUrl not publicURL
    const { data: urlData } = _supabase.storage.from(bucket).getPublicUrl(fileName);
    const publicUrl = urlData.publicUrl;
    const { error: updateError } = await _supabase
      .from("partners" as never)
      .update({ logo_url: publicUrl } as never)
      .eq("id" as never, partnerId as never);
    if (updateError) throw updateError;
    return publicUrl;
  } catch (e) {
    console.error("[Supabase] uploadPartnerLogo failed", e);
    throw e;
  }
}
